# Generated by Django 6.0.3 on 2026-03-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmenttracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
