# Generated by Django 6.0.3 on 2026-03-15 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmenttracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={},
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='category',
            field=models.CharField(default='ASSIGNMENT', max_length=20),
        ),
        migrations.AlterField(
            model_name='subject',
            name='days',
            field=models.CharField(max_length=50),
        ),
    ]
