# Generated by Django 6.0.3 on 2026-03-14 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmenttracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
