# Generated by Django 6.0.3 on 2026-03-14 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignmenttracker', '0002_assignment_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='category',
            field=models.CharField(choices=[('EXAM', 'Exam'), ('PROJECT', 'Project'), ('TEST', 'Test'), ('ASSIGNMENT', 'Assignment'), ('OTHERS', 'Others')], default='ASSIGNMENT', max_length=20),
        ),
    ]
